title: "Proyecto de Análisis de Datos"
description: "Análisis de criminalidad y factores económicos en Chile"
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag



# remote_theme: pages-themes/time-machine@v0.2.0
# plugins:
#  - jekyll-remote-theme
markdown: kramdown


header_pages:
  - about.md

include:
  - figuras

assets:
  - figuras
  
author:
  name: "Contacto"
  email: "jgarciat4@estudiante.uc.cl - mlozadap@estudiante.uc.cl"

feed:
  path: "feed.xml"
